/**
 * Master directory of every FIDE-recognized national federation (Phase 0 W7
 * expansion, 2026-05-14).
 *
 * Source of truth: FIDE handbook "F. Federations Directory" + FIDE continental
 * federation membership (ECU, FIDE-Americas, ACF, ACC, FOC). Coverage is the
 * ~199 member federations as of 2024–2026 council.
 *
 * This const is the SEED for the `federations` table. The DB row is the
 * runtime source of truth — `rating_list_url`, `scrape_strategy`, `active`
 * may drift over time via small migrations as parsers ship. We update this
 * const opportunistically.
 *
 * Notable FIDE/ISO mismatches preserved here:
 *   FIDE ENG/SCO/WLS → ISO GB sub-countries (no unique alpha-3)
 *   FIDE GER         → ISO DE / DEU
 *   FIDE NED         → ISO NL / NLD
 *   FIDE SUI         → ISO CH / CHE
 *   FIDE TPE         → ISO TW / TWN (Chinese Taipei)
 *   FIDE IRI         → ISO IR / IRN
 *   FIDE INA         → ISO ID / IDN
 *   FIDE FAI         → ISO FO / FRO (Faroe Islands)
 *   FIDE GUE/JCI/IOM → ISO Crown Dependencies (no unique alpha-3 in some lists)
 *
 * Continent classification follows FIDE Continental Federation:
 *   EU = European Chess Union (ECU)
 *   NA = FIDE-Americas (north) — Mexico is grouped here per FIDE
 *   SA = FIDE-Americas (south)
 *   AS = Asian Chess Federation (ACF)
 *   AF = African Chess Confederation (ACC)
 *   OC = Oceania Chess Confederation (FOC)
 */

export type ScrapeStrategy =
  | 'dump' //         download zipped/CSV/XML — cluster A
  | 'fetch-html' //   fetch() + cheerio — cluster B
  | 'aspnet' //       ASP.NET ViewState postback — cluster C
  | 'spa' //          Playwright SPA render — cluster D
  | 'api' //          JSON REST endpoint — cluster E
  | 'cloudflare' //   Playwright behind Cloudflare — cluster F
  | 'placeholder'; // no native list yet — cluster G

export type Continent = 'AF' | 'AS' | 'EU' | 'NA' | 'OC' | 'SA';

export type SyncCadence = 'monthly' | 'quarterly' | 'semi_annual' | 'manual';

export type RatingListFormat = 'xml' | 'csv' | 'json' | 'html';

export interface FederationDirectoryEntry {
  /** FIDE 3-letter code (primary key in `federations.id`). */
  code: string;
  /** Authoritative full name in English. */
  name: string;
  /** ISO 3166-1 alpha-2. null only for FIDE itself. */
  iso2: string | null;
  /** ISO 3166-1 alpha-3. null for sub-country federations (ENG/SCO/WLS). */
  iso3: string | null;
  continent: Continent | null;
  /** Best-known public rating-list URL. May rot — verify when building parser. */
  ratingListUrl: string | null;
  /** Source format (drives the parser file). null where unknown. */
  ratingListFormat: RatingListFormat | null;
  /** Cluster hint — drives wave bucketing and helper choice. */
  scrapeStrategy: ScrapeStrategy;
  /** Coarse order-of-magnitude — used to size batches + show on roster header. */
  estPlayerCount: number | null;
  /** How often the federation publishes a fresh list. */
  syncCadence: SyncCadence;
  /** true only once the bespoke worker ships; default false. */
  active: boolean;
  /** Freeform notes: bot wall caveats, URL flux warnings, paid-membership gates. */
  notes?: string;
}

/**
 * All ~199 FIDE-recognized federations, in alphabetical order by code.
 *
 * Wave-0 active rows (FIDE, ICF, USCF) preserve their existing `active` state
 * via the migration's ON CONFLICT clause — never overwritten by this seed.
 */
export const FEDERATION_DIRECTORY: readonly FederationDirectoryEntry[] = [
  // ─── International umbrella ────────────────────────────────────────────────
  {
    code: 'FIDE',
    name: 'International Chess Federation',
    iso2: null,
    iso3: null,
    continent: null,
    ratingListUrl: 'https://ratings.fide.com/download.phtml',
    ratingListFormat: 'xml',
    scrapeStrategy: 'dump',
    estPlayerCount: 755_000,
    syncCadence: 'monthly',
    active: true,
    notes: 'Monthly XML zip dumps for standard/rapid/blitz',
  },

  // ─── Europe (ECU) ──────────────────────────────────────────────────────────
  {
    code: 'ALB',
    name: 'Federation Albanian Chess',
    iso2: 'AL',
    iso3: 'ALB',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'AND',
    name: 'Federacio d’Escacs Valls d’Andorra',
    iso2: 'AD',
    iso3: 'AND',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'Microstate',
  },
  {
    code: 'ARM',
    name: 'Chess Federation of Armenia',
    iso2: 'AM',
    iso3: 'ARM',
    continent: 'EU',
    ratingListUrl: 'https://armchess.am',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'Highest GM density per capita',
  },
  {
    code: 'AUT',
    name: 'Österreichischer Schachbund',
    iso2: 'AT',
    iso3: 'AUT',
    continent: 'EU',
    ratingListUrl: 'https://chess.at/ratings',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 7000,
    syncCadence: 'monthly',
    active: false,
  },
  {
    code: 'AZE',
    name: 'Azerbaijan Chess Federation',
    iso2: 'AZ',
    iso3: 'AZE',
    continent: 'EU',
    ratingListUrl: 'https://azchess.az',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'BLR',
    name: 'Belarus Chess Federation',
    iso2: 'BY',
    iso3: 'BLR',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 4000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'BEL',
    name: 'KBSB-FRBE Belgium',
    iso2: 'BE',
    iso3: 'BEL',
    continent: 'EU',
    ratingListUrl: 'https://www.kbsb.be/index.php/en/ratings',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 5000,
    syncCadence: 'monthly',
    active: false,
    notes: 'Phase 1 W10 target',
  },
  {
    code: 'BIH',
    name: 'Chess Federation of Bosnia and Herzegovina',
    iso2: 'BA',
    iso3: 'BIH',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 3000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'BUL',
    name: 'Bulgarian Chess Federation',
    iso2: 'BG',
    iso3: 'BGR',
    continent: 'EU',
    ratingListUrl: 'https://chessbg.com',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'CRO',
    name: 'Croatian Chess Federation',
    iso2: 'HR',
    iso3: 'HRV',
    continent: 'EU',
    ratingListUrl: 'https://hssahkr.hr',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 4000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'CYP',
    name: 'Cyprus Chess Federation',
    iso2: 'CY',
    iso3: 'CYP',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 800,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'CZE',
    name: 'Šachový svaz České republiky',
    iso2: 'CZ',
    iso3: 'CZE',
    continent: 'EU',
    ratingListUrl: 'https://chess.cz/lkr',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 12_000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'DEN',
    name: 'Dansk Skak Union',
    iso2: 'DK',
    iso3: 'DNK',
    continent: 'EU',
    ratingListUrl: 'https://skak.dk',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'DSB',
    name: 'Deutscher Schachbund',
    iso2: 'DE',
    iso3: 'DEU',
    continent: 'EU',
    ratingListUrl: 'https://www.schachbund.de/dwz.html',
    ratingListFormat: 'csv',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 110_000,
    syncCadence: 'monthly',
    active: false,
    notes:
      'DWZ ~50 ELO below FIDE; persist raw. FIDE alpha-3 is GER; we use DSB as PK to match existing seed.',
  },
  {
    code: 'ECF',
    name: 'English Chess Federation',
    iso2: 'GB',
    iso3: null,
    continent: 'EU',
    ratingListUrl: 'https://www.englishchess.org.uk/ecf-publications/',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 12_000,
    syncCadence: 'monthly',
    active: false,
    notes: 'FIDE alpha-3 is ENG; we use ECF as PK to match existing seed.',
  },
  {
    code: 'EST',
    name: 'Eesti Maleliit',
    iso2: 'EE',
    iso3: 'EST',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 2000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'FAI',
    name: 'Føroyski Talvfelagið',
    iso2: 'FO',
    iso3: 'FRO',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'Faroe Islands',
  },
  {
    code: 'FFE',
    name: 'Fédération Française des Échecs',
    iso2: 'FR',
    iso3: 'FRA',
    continent: 'EU',
    ratingListUrl: 'https://www.echecs.asso.fr/Default.aspx?Cat=4',
    ratingListFormat: 'html',
    scrapeStrategy: 'aspnet',
    estPlayerCount: 57_000,
    syncCadence: 'monthly',
    active: false,
    notes: 'ASP.NET ViewState. FIDE alpha-3 is FRA; we use FFE as PK to match existing seed.',
  },
  {
    code: 'FIN',
    name: 'Suomen Shakkiliitto',
    iso2: 'FI',
    iso3: 'FIN',
    continent: 'EU',
    ratingListUrl: 'https://shakkiliitto.fi',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'GEO',
    name: 'Georgian Chess Federation',
    iso2: 'GE',
    iso3: 'GEO',
    continent: 'EU',
    ratingListUrl: 'https://gcf.org.ge',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 4000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'Top women’s chess',
  },
  {
    code: 'GIB',
    name: 'Gibraltar Chess Association',
    iso2: 'GI',
    iso3: 'GIB',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'GRE',
    name: 'Greek Chess Federation',
    iso2: 'GR',
    iso3: 'GRC',
    continent: 'EU',
    ratingListUrl: 'https://chessfed.gr',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'GUE',
    name: 'Guernsey Chess Federation',
    iso2: 'GG',
    iso3: null,
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'HUN',
    name: 'Magyar Sakkszövetség',
    iso2: 'HU',
    iso3: 'HUN',
    continent: 'EU',
    ratingListUrl: 'https://www.chess.hu',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 10_000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'Top-10 historical',
  },
  {
    code: 'FSI',
    name: 'Federazione Scacchistica Italiana',
    iso2: 'IT',
    iso3: 'ITA',
    continent: 'EU',
    ratingListUrl: 'https://www.federscacchi.it/str.php',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 28_000,
    syncCadence: 'monthly',
    active: false,
    notes: 'FIDE alpha-3 is ITA; we use FSI as PK to match existing seed.',
  },
  {
    code: 'ICF',
    name: 'Israel Chess Federation',
    iso2: 'IL',
    iso3: 'ISR',
    continent: 'EU',
    ratingListUrl: 'https://www.chess.org.il/Players/PlayersRanking.aspx',
    ratingListFormat: 'html',
    scrapeStrategy: 'aspnet',
    estPlayerCount: 6800,
    syncCadence: 'monthly',
    active: true,
    notes: 'ASP.NET GridView. FIDE alpha-3 is ISR; we use ICF as PK to match existing seed.',
  },
  {
    code: 'ISL',
    name: 'Skáksamband Íslands',
    iso2: 'IS',
    iso3: 'ISL',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'IRL',
    name: 'Irish Chess Union',
    iso2: 'IE',
    iso3: 'IRL',
    continent: 'EU',
    ratingListUrl: 'https://www.icu.ie/players',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 2000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'JCI',
    name: 'Jersey Chess Federation',
    iso2: 'JE',
    iso3: null,
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'KAZ',
    name: 'Kazakhstan Chess Federation',
    iso2: 'KZ',
    iso3: 'KAZ',
    continent: 'AS',
    ratingListUrl: 'https://kazchess.kz',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 5000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'Emerging; federated with ACF',
  },
  {
    code: 'KOS',
    name: 'Kosova Chess Federation',
    iso2: 'XK',
    iso3: null,
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 800,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'XK is unofficial alpha-2',
  },
  {
    code: 'LAT',
    name: 'Latvijas Šaha Federācija',
    iso2: 'LV',
    iso3: 'LVA',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 2000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'LIE',
    name: 'Liechtensteiner Schachverband',
    iso2: 'LI',
    iso3: 'LIE',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'Microstate',
  },
  {
    code: 'LTU',
    name: 'Lietuvos Šachmatų Federacija',
    iso2: 'LT',
    iso3: 'LTU',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 2500,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'LUX',
    name: 'Fédération Luxembourgeoise des Échecs',
    iso2: 'LU',
    iso3: 'LUX',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MDA',
    name: 'Federaţia Şahului din Moldova',
    iso2: 'MD',
    iso3: 'MDA',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'MKD',
    name: 'Chess Federation of North Macedonia',
    iso2: 'MK',
    iso3: 'MKD',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'MLT',
    name: 'Malta Chess Federation',
    iso2: 'MT',
    iso3: 'MLT',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MNC',
    name: 'Fédération Monégasque des Échecs',
    iso2: 'MC',
    iso3: 'MCO',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'Microstate',
  },
  {
    code: 'MNE',
    name: 'Chess Federation of Montenegro',
    iso2: 'ME',
    iso3: 'MNE',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 800,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'NED',
    name: 'Koninklijke Nederlandse Schaakbond',
    iso2: 'NL',
    iso3: 'NLD',
    continent: 'EU',
    ratingListUrl: 'https://ratingviewer.nl',
    ratingListFormat: 'html',
    scrapeStrategy: 'spa',
    estPlayerCount: 17_000,
    syncCadence: 'monthly',
    active: false,
    notes: 'KNSB in PLAN.md; SPA needs Playwright',
  },
  {
    code: 'NOR',
    name: 'Norges Sjakkforbund',
    iso2: 'NO',
    iso3: 'NOR',
    continent: 'EU',
    ratingListUrl: 'https://sjakkforbundet.no',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 4000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'Magnus’s federation',
  },
  {
    code: 'POL',
    name: 'Polski Związek Szachowy',
    iso2: 'PL',
    iso3: 'POL',
    continent: 'EU',
    ratingListUrl: 'https://cr.pzszach.pl',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 30_000,
    syncCadence: 'monthly',
    active: false,
    notes: 'PZSzach in PLAN.md',
  },
  {
    code: 'POR',
    name: 'Federação Portuguesa de Xadrez',
    iso2: 'PT',
    iso3: 'PRT',
    continent: 'EU',
    ratingListUrl: 'https://www.fpx.pt',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'ROU',
    name: 'Federația Română de Şah',
    iso2: 'RO',
    iso3: 'ROU',
    continent: 'EU',
    ratingListUrl: 'https://www.frsah.ro',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 6000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'RUS',
    name: 'Chess Federation of Russia',
    iso2: 'RU',
    iso3: 'RUS',
    continent: 'EU',
    ratingListUrl: 'https://ratings.ruchess.ru',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 120_000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'Politically sensitive; large pool',
  },
  {
    code: 'SCO',
    name: 'Chess Scotland',
    iso2: 'GB',
    iso3: null,
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'quarterly',
    active: false,
    notes: 'FIDE sub-country',
  },
  {
    code: 'SMR',
    name: 'Federazione Scacchistica di San Marino',
    iso2: 'SM',
    iso3: 'SMR',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'Microstate',
  },
  {
    code: 'SRB',
    name: 'Šahovski savez Srbije',
    iso2: 'RS',
    iso3: 'SRB',
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 8000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'SVK',
    name: 'Slovak Chess Federation',
    iso2: 'SK',
    iso3: 'SVK',
    continent: 'EU',
    ratingListUrl: 'https://www.chess.sk',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'SLO',
    name: 'Šahovska zveza Slovenije',
    iso2: 'SI',
    iso3: 'SVN',
    continent: 'EU',
    ratingListUrl: 'https://www.sah-zveza.si',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 2000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'ESP',
    name: 'Federación Española de Ajedrez',
    iso2: 'ES',
    iso3: 'ESP',
    continent: 'EU',
    ratingListUrl: 'https://www.feda.org/feda2k16/ranking.aspx',
    ratingListFormat: 'html',
    scrapeStrategy: 'aspnet',
    estPlayerCount: 28_000,
    syncCadence: 'monthly',
    active: false,
    notes: 'FEDA in PLAN.md',
  },
  {
    code: 'SWE',
    name: 'Sveriges Schackförbund',
    iso2: 'SE',
    iso3: 'SWE',
    continent: 'EU',
    ratingListUrl: 'https://www.schack.se/rating',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 5000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'SUI',
    name: 'Swiss Chess Federation',
    iso2: 'CH',
    iso3: 'CHE',
    continent: 'EU',
    ratingListUrl: 'https://www.swisschess.ch',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 6000,
    syncCadence: 'monthly',
    active: false,
  },
  {
    code: 'TUR',
    name: 'Türkiye Satranç Federasyonu',
    iso2: 'TR',
    iso3: 'TUR',
    continent: 'EU',
    ratingListUrl: 'https://tsf.org.tr',
    ratingListFormat: 'html',
    scrapeStrategy: 'spa',
    estPlayerCount: 15_000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'SPA needs Playwright',
  },
  {
    code: 'UKR',
    name: 'Ukrainian Chess Federation',
    iso2: 'UA',
    iso3: 'UKR',
    continent: 'EU',
    ratingListUrl: 'https://chess-ratings.com.ua',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 50_000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'Strong chess country',
  },
  {
    code: 'WLS',
    name: 'Welsh Chess Union',
    iso2: 'GB',
    iso3: null,
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'FIDE sub-country',
  },
  {
    code: 'IOM',
    name: 'Isle of Man Chess Union',
    iso2: 'IM',
    iso3: null,
    continent: 'EU',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },

  // ─── Americas (north + south) — FIDE Americas zone ────────────────────────
  {
    code: 'AHO',
    name: 'Curaçao Chess Federation',
    iso2: 'CW',
    iso3: 'CUW',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'Former Netherlands Antilles',
  },
  {
    code: 'ARG',
    name: 'Federación Argentina de Ajedrez',
    iso2: 'AR',
    iso3: 'ARG',
    continent: 'SA',
    ratingListUrl: 'https://www.fada.org.ar',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 5000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'ARU',
    name: 'Chess Federation of Aruba',
    iso2: 'AW',
    iso3: 'ABW',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 150,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'BAH',
    name: 'Bahamas Chess Federation',
    iso2: 'BS',
    iso3: 'BHS',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'BAR',
    name: 'Barbados Chess Federation',
    iso2: 'BB',
    iso3: 'BRB',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'BER',
    name: 'Bermuda Chess Association',
    iso2: 'BM',
    iso3: 'BMU',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'BIZ',
    name: 'National Chess Federation of Belize',
    iso2: 'BZ',
    iso3: 'BLZ',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'BOL',
    name: 'Federación Boliviana de Ajedrez',
    iso2: 'BO',
    iso3: 'BOL',
    continent: 'SA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'BRA',
    name: 'Confederação Brasileira de Xadrez',
    iso2: 'BR',
    iso3: 'BRA',
    continent: 'SA',
    ratingListUrl: 'https://www.cbx.org.br/rating',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 10_000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'Largest LatAm pool',
  },
  {
    code: 'CAN',
    name: 'Chess Federation of Canada',
    iso2: 'CA',
    iso3: 'CAN',
    continent: 'NA',
    ratingListUrl: 'https://www.chess.ca/en/ratings/',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 9000,
    syncCadence: 'monthly',
    active: false,
    notes: 'CFC in PLAN.md',
  },
  {
    code: 'CAY',
    name: 'Cayman Islands Chess Federation',
    iso2: 'KY',
    iso3: 'CYM',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'CHI',
    name: 'Federación Nacional de Ajedrez de Chile',
    iso2: 'CL',
    iso3: 'CHL',
    continent: 'SA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 2000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'COL',
    name: 'Federación Colombiana de Ajedrez',
    iso2: 'CO',
    iso3: 'COL',
    continent: 'SA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 2500,
    syncCadence: 'quarterly',
    active: false,
    notes: 'FECODAZ',
  },
  {
    code: 'CRC',
    name: 'Federación Costarricense de Ajedrez',
    iso2: 'CR',
    iso3: 'CRI',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'CUB',
    name: 'Federación Cubana de Ajedrez',
    iso2: 'CU',
    iso3: 'CUB',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 2500,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'DOM',
    name: 'Federación Dominicana de Ajedrez',
    iso2: 'DO',
    iso3: 'DOM',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'ECU',
    name: 'Federación Ecuatoriana de Ajedrez',
    iso2: 'EC',
    iso3: 'ECU',
    continent: 'SA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'ESA',
    name: 'Federación Salvadoreña de Ajedrez',
    iso2: 'SV',
    iso3: 'SLV',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 400,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'GUA',
    name: 'Federación Nacional de Ajedrez de Guatemala',
    iso2: 'GT',
    iso3: 'GTM',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'GUY',
    name: 'Guyana Chess Federation',
    iso2: 'GY',
    iso3: 'GUY',
    continent: 'SA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'HAI',
    name: 'Fédération Haïtienne des Échecs',
    iso2: 'HT',
    iso3: 'HTI',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'HON',
    name: 'Federación Nacional de Ajedrez de Honduras',
    iso2: 'HN',
    iso3: 'HND',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'IVB',
    name: 'British Virgin Islands Chess Federation',
    iso2: 'VG',
    iso3: 'VGB',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'ISV',
    name: 'US Virgin Islands Chess Federation',
    iso2: 'VI',
    iso3: 'VIR',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'JAM',
    name: 'Jamaica Chess Federation',
    iso2: 'JM',
    iso3: 'JAM',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MEX',
    name: 'Federación Nacional de Ajedrez de México',
    iso2: 'MX',
    iso3: 'MEX',
    continent: 'NA',
    ratingListUrl: 'https://www.fenamac.com',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'FENAMAC in PLAN.md',
  },
  {
    code: 'NCA',
    name: 'Federación Nicaragüense de Ajedrez',
    iso2: 'NI',
    iso3: 'NIC',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'PAN',
    name: 'Federación Panameña de Ajedrez',
    iso2: 'PA',
    iso3: 'PAN',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 400,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'PAR',
    name: 'Federación Paraguaya de Ajedrez',
    iso2: 'PY',
    iso3: 'PRY',
    continent: 'SA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'PER',
    name: 'Federación Deportiva Peruana de Ajedrez',
    iso2: 'PE',
    iso3: 'PER',
    continent: 'SA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 2000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'PUR',
    name: 'Federación de Ajedrez de Puerto Rico',
    iso2: 'PR',
    iso3: 'PRI',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SUR',
    name: 'Surinaamse Schaakbond',
    iso2: 'SR',
    iso3: 'SUR',
    continent: 'SA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'TRI',
    name: 'Trinidad and Tobago Chess Association',
    iso2: 'TT',
    iso3: 'TTO',
    continent: 'NA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'URU',
    name: 'Federación Uruguaya de Ajedrez',
    iso2: 'UY',
    iso3: 'URY',
    continent: 'SA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 800,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'USCF',
    name: 'US Chess Federation',
    iso2: 'US',
    iso3: 'USA',
    continent: 'NA',
    ratingListUrl: 'https://www.uschess.org/datapage/',
    ratingListFormat: 'html',
    scrapeStrategy: 'cloudflare',
    estPlayerCount: 25_000,
    syncCadence: 'monthly',
    active: false,
    notes:
      'Cloudflare-blocked 2026-05-13; FIDE-USA slice (13k) is the active fallback. FIDE alpha-3 is USA; we use USCF as PK to match existing seed.',
  },
  {
    code: 'VEN',
    name: 'Federación Venezolana de Ajedrez',
    iso2: 'VE',
    iso3: 'VEN',
    continent: 'SA',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'quarterly',
    active: false,
  },

  // ─── Asia (ACF) ────────────────────────────────────────────────────────────
  {
    code: 'AFG',
    name: 'Afghanistan Chess Federation',
    iso2: 'AF',
    iso3: 'AFG',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'BAN',
    name: 'Bangladesh Chess Federation',
    iso2: 'BD',
    iso3: 'BGD',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'BHU',
    name: 'Bhutan Chess Federation',
    iso2: 'BT',
    iso3: 'BTN',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'BRU',
    name: 'Brunei Darussalam Chess Federation',
    iso2: 'BN',
    iso3: 'BRN',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'CAM',
    name: 'Cambodia Chess Federation',
    iso2: 'KH',
    iso3: 'KHM',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'CHN',
    name: 'Chinese Chess Association',
    iso2: 'CN',
    iso3: 'CHN',
    continent: 'AS',
    ratingListUrl: 'https://www.chinachess.org.cn',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 8000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'CCA in PLAN.md; public data restricted',
  },
  {
    code: 'HKG',
    name: 'Hong Kong Chess Federation',
    iso2: 'HK',
    iso3: 'HKG',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'IND',
    name: 'All India Chess Federation',
    iso2: 'IN',
    iso3: 'IND',
    continent: 'AS',
    ratingListUrl: 'https://www.aicf.in/ratings',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 35_000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'AICF in PLAN.md; geo-blocked from marketplace',
  },
  {
    code: 'INA',
    name: 'Persatuan Catur Seluruh Indonesia (PERCASI)',
    iso2: 'ID',
    iso3: 'IDN',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 2000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'IRI',
    name: 'Iran Chess Federation',
    iso2: 'IR',
    iso3: 'IRN',
    continent: 'AS',
    ratingListUrl: 'https://iranchessfederation.ir',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'Sanctions check on payments',
  },
  {
    code: 'IRQ',
    name: 'Iraqi Chess Federation',
    iso2: 'IQ',
    iso3: 'IRQ',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'JOR',
    name: 'Jordan Chess Federation',
    iso2: 'JO',
    iso3: 'JOR',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'JPN',
    name: 'Japan Chess Association',
    iso2: 'JP',
    iso3: 'JPN',
    continent: 'AS',
    ratingListUrl: 'https://japanchess.org',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'KGZ',
    name: 'Kyrgyzstan Chess Federation',
    iso2: 'KG',
    iso3: 'KGZ',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 400,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'KOR',
    name: 'Korea Chess Federation',
    iso2: 'KR',
    iso3: 'KOR',
    continent: 'AS',
    ratingListUrl: 'https://koreachess.org',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'KUW',
    name: 'Kuwait Chess Federation',
    iso2: 'KW',
    iso3: 'KWT',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'LAO',
    name: 'Lao Chess Federation',
    iso2: 'LA',
    iso3: 'LAO',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'LBN',
    name: 'Lebanese Chess Federation',
    iso2: 'LB',
    iso3: 'LBN',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MAC',
    name: 'Macau Chess Association',
    iso2: 'MO',
    iso3: 'MAC',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MAS',
    name: 'Malaysian Chess Federation',
    iso2: 'MY',
    iso3: 'MYS',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'MDV',
    name: 'Chess Association of Maldives',
    iso2: 'MV',
    iso3: 'MDV',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MGL',
    name: 'Mongolian Chess Federation',
    iso2: 'MN',
    iso3: 'MNG',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 800,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MYA',
    name: 'Myanmar Chess Federation',
    iso2: 'MM',
    iso3: 'MMR',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'NEP',
    name: 'Nepal Chess Association',
    iso2: 'NP',
    iso3: 'NPL',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'PAK',
    name: 'Chess Federation of Pakistan',
    iso2: 'PK',
    iso3: 'PAK',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1000,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'PHI',
    name: 'National Chess Federation of the Philippines',
    iso2: 'PH',
    iso3: 'PHL',
    continent: 'AS',
    ratingListUrl: 'https://www.ncfp.org.ph',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 5000,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'PLE',
    name: 'Palestine Chess Federation',
    iso2: 'PS',
    iso3: 'PSE',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'PRK',
    name: 'Democratic People’s Republic of Korea Chess Federation',
    iso2: 'KP',
    iso3: 'PRK',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'manual',
    active: false,
    notes: 'North Korea; limited data',
  },
  {
    code: 'QAT',
    name: 'Qatar Chess Federation',
    iso2: 'QA',
    iso3: 'QAT',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'KSA',
    name: 'Saudi Chess Association',
    iso2: 'SA',
    iso3: 'SAU',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SGP',
    name: 'Singapore Chess Federation',
    iso2: 'SG',
    iso3: 'SGP',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 800,
    syncCadence: 'quarterly',
    active: false,
  },
  {
    code: 'SRI',
    name: 'Chess Federation of Sri Lanka',
    iso2: 'LK',
    iso3: 'LKA',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 800,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SYR',
    name: 'Syrian Chess Federation',
    iso2: 'SY',
    iso3: 'SYR',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'TJK',
    name: 'Tajikistan Chess Federation',
    iso2: 'TJ',
    iso3: 'TJK',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'TKM',
    name: 'Turkmenistan Chess Federation',
    iso2: 'TM',
    iso3: 'TKM',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'TLS',
    name: 'Timor-Leste Chess Federation',
    iso2: 'TL',
    iso3: 'TLS',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'TPE',
    name: 'Chinese Taipei Chess Association',
    iso2: 'TW',
    iso3: 'TWN',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'FIDE uses TPE for Taiwan',
  },
  {
    code: 'UAE',
    name: 'United Arab Emirates Chess Federation',
    iso2: 'AE',
    iso3: 'ARE',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'UZB',
    name: 'Uzbekistan Chess Federation',
    iso2: 'UZ',
    iso3: 'UZB',
    continent: 'AS',
    ratingListUrl: 'https://chess.uz',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 4000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'Emerging',
  },
  {
    code: 'VIE',
    name: 'Vietnam Chess Federation',
    iso2: 'VN',
    iso3: 'VNM',
    continent: 'AS',
    ratingListUrl: 'https://vietnamchess.vn',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'YEM',
    name: 'Yemen Chess Federation',
    iso2: 'YE',
    iso3: 'YEM',
    continent: 'AS',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },

  // ─── Africa (ACC) ──────────────────────────────────────────────────────────
  {
    code: 'ALG',
    name: 'Fédération Algérienne des Échecs',
    iso2: 'DZ',
    iso3: 'DZA',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'ANG',
    name: 'Federação Angolana de Xadrez',
    iso2: 'AO',
    iso3: 'AGO',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'BDI',
    name: 'Fédération Burundaise des Échecs',
    iso2: 'BI',
    iso3: 'BDI',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'BEN',
    name: 'Fédération Béninoise des Échecs',
    iso2: 'BJ',
    iso3: 'BEN',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'BOT',
    name: 'Botswana Chess Federation',
    iso2: 'BW',
    iso3: 'BWA',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'BUR',
    name: 'Fédération Burkinabé des Échecs',
    iso2: 'BF',
    iso3: 'BFA',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'CAF',
    name: 'Fédération Centrafricaine des Échecs',
    iso2: 'CF',
    iso3: 'CAF',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'CGO',
    name: 'Fédération Congolaise des Échecs',
    iso2: 'CG',
    iso3: 'COG',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'CHA',
    name: 'Fédération Tchadienne des Échecs',
    iso2: 'TD',
    iso3: 'TCD',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'CIV',
    name: 'Fédération Ivoirienne des Échecs',
    iso2: 'CI',
    iso3: 'CIV',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 400,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'CMR',
    name: 'Fédération Camerounaise des Échecs',
    iso2: 'CM',
    iso3: 'CMR',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 400,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'COD',
    name: 'Fédération Congolaise des Échecs (RDC)',
    iso2: 'CD',
    iso3: 'COD',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 400,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'DRC',
  },
  {
    code: 'COM',
    name: 'Comoros Chess Federation',
    iso2: 'KM',
    iso3: 'COM',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'CPV',
    name: 'Federação Cabo-Verdiana de Xadrez',
    iso2: 'CV',
    iso3: 'CPV',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'DJI',
    name: 'Fédération Djiboutienne des Échecs',
    iso2: 'DJ',
    iso3: 'DJI',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'EGY',
    name: 'Egyptian Chess Federation',
    iso2: 'EG',
    iso3: 'EGY',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 3000,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'ERI',
    name: 'Eritrea Chess Federation',
    iso2: 'ER',
    iso3: 'ERI',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'ETH',
    name: 'Ethiopian Chess Federation',
    iso2: 'ET',
    iso3: 'ETH',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'GAB',
    name: 'Fédération Gabonaise des Échecs',
    iso2: 'GA',
    iso3: 'GAB',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'GAM',
    name: 'Gambia Chess Federation',
    iso2: 'GM',
    iso3: 'GMB',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'GEQ',
    name: 'Equatorial Guinea Chess Federation',
    iso2: 'GQ',
    iso3: 'GNQ',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'GHA',
    name: 'Ghana Chess Association',
    iso2: 'GH',
    iso3: 'GHA',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 400,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'GUI',
    name: 'Fédération Guinéenne des Échecs',
    iso2: 'GN',
    iso3: 'GIN',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'KEN',
    name: 'Chess Kenya',
    iso2: 'KE',
    iso3: 'KEN',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 800,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'LBR',
    name: 'Liberia Chess Federation',
    iso2: 'LR',
    iso3: 'LBR',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'LBY',
    name: 'Libyan Chess Federation',
    iso2: 'LY',
    iso3: 'LBY',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'LES',
    name: 'Lesotho Chess Federation',
    iso2: 'LS',
    iso3: 'LSO',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MAD',
    name: 'Fédération Malgache des Échecs',
    iso2: 'MG',
    iso3: 'MDG',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MAR',
    name: 'Fédération Royale Marocaine des Échecs',
    iso2: 'MA',
    iso3: 'MAR',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'Morocco',
  },
  {
    code: 'MAW',
    name: 'Chess Association of Malawi',
    iso2: 'MW',
    iso3: 'MWI',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MLI',
    name: 'Fédération Malienne des Échecs',
    iso2: 'ML',
    iso3: 'MLI',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MOZ',
    name: 'Federação Moçambicana de Xadrez',
    iso2: 'MZ',
    iso3: 'MOZ',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MRI',
    name: 'Mauritius Chess Federation',
    iso2: 'MU',
    iso3: 'MUS',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'MTN',
    name: 'Fédération Mauritanienne des Échecs',
    iso2: 'MR',
    iso3: 'MRT',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'NAM',
    name: 'Namibia Chess Federation',
    iso2: 'NA',
    iso3: 'NAM',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'NGR',
    name: 'Nigeria Chess Federation',
    iso2: 'NG',
    iso3: 'NGA',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'NIG',
    name: 'Fédération Nigérienne des Échecs',
    iso2: 'NE',
    iso3: 'NER',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'Niger (not Nigeria)',
  },
  {
    code: 'RSA',
    name: 'Chess South Africa',
    iso2: 'ZA',
    iso3: 'ZAF',
    continent: 'AF',
    ratingListUrl: 'https://www.chessa.co.za',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 3000,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'CHESSA in PLAN.md',
  },
  {
    code: 'RWA',
    name: 'Rwanda Chess Federation',
    iso2: 'RW',
    iso3: 'RWA',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SEN',
    name: 'Fédération Sénégalaise des Échecs',
    iso2: 'SN',
    iso3: 'SEN',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SEY',
    name: 'Seychelles Chess Federation',
    iso2: 'SC',
    iso3: 'SYC',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SLE',
    name: 'Sierra Leone Chess Federation',
    iso2: 'SL',
    iso3: 'SLE',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SOM',
    name: 'Somali Chess Federation',
    iso2: 'SO',
    iso3: 'SOM',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SSD',
    name: 'South Sudan Chess Federation',
    iso2: 'SS',
    iso3: 'SSD',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'STP',
    name: 'São Tomé and Príncipe Chess Federation',
    iso2: 'ST',
    iso3: 'STP',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SUD',
    name: 'Sudan Chess Federation',
    iso2: 'SD',
    iso3: 'SDN',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 300,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SWZ',
    name: 'Eswatini Chess Federation',
    iso2: 'SZ',
    iso3: 'SWZ',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'Formerly Swaziland',
  },
  {
    code: 'TAN',
    name: 'Tanzania Chess Federation',
    iso2: 'TZ',
    iso3: 'TZA',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 400,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'TOG',
    name: 'Fédération Togolaise des Échecs',
    iso2: 'TG',
    iso3: 'TGO',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'TUN',
    name: 'Fédération Tunisienne des Échecs',
    iso2: 'TN',
    iso3: 'TUN',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 1500,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'UGA',
    name: 'Uganda Chess Federation',
    iso2: 'UG',
    iso3: 'UGA',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 400,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'ZAM',
    name: 'Chess Federation of Zambia',
    iso2: 'ZM',
    iso3: 'ZMB',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 400,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'ZIM',
    name: 'Zimbabwe Chess Federation',
    iso2: 'ZW',
    iso3: 'ZWE',
    continent: 'AF',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 400,
    syncCadence: 'semi_annual',
    active: false,
  },

  // ─── Oceania (FOC) ─────────────────────────────────────────────────────────
  {
    code: 'AUS',
    name: 'Australian Chess Federation',
    iso2: 'AU',
    iso3: 'AUS',
    continent: 'OC',
    ratingListUrl: 'https://auschess.org.au/rating/',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 5000,
    syncCadence: 'quarterly',
    active: false,
    notes: 'ACF in PLAN.md; quarterly periods',
  },
  {
    code: 'COK',
    name: 'Cook Islands Chess Federation',
    iso2: 'CK',
    iso3: 'COK',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 50,
    syncCadence: 'manual',
    active: false,
  },
  {
    code: 'FIJ',
    name: 'Fiji Chess Federation',
    iso2: 'FJ',
    iso3: 'FJI',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'FSM',
    name: 'Federated States of Micronesia Chess Federation',
    iso2: 'FM',
    iso3: 'FSM',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 50,
    syncCadence: 'manual',
    active: false,
  },
  {
    code: 'GUM',
    name: 'Guam Chess Federation',
    iso2: 'GU',
    iso3: 'GUM',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'KIR',
    name: 'Kiribati Chess Federation',
    iso2: 'KI',
    iso3: 'KIR',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 50,
    syncCadence: 'manual',
    active: false,
  },
  {
    code: 'MHL',
    name: 'Marshall Islands Chess Federation',
    iso2: 'MH',
    iso3: 'MHL',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 50,
    syncCadence: 'manual',
    active: false,
  },
  {
    code: 'NMA',
    name: 'Northern Mariana Islands Chess Federation',
    iso2: 'MP',
    iso3: 'MNP',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 50,
    syncCadence: 'manual',
    active: false,
  },
  {
    code: 'NRU',
    name: 'Nauru Chess Federation',
    iso2: 'NR',
    iso3: 'NRU',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 50,
    syncCadence: 'manual',
    active: false,
  },
  {
    code: 'NZL',
    name: 'New Zealand Chess Federation',
    iso2: 'NZ',
    iso3: 'NZL',
    continent: 'OC',
    ratingListUrl: 'https://www.newzealandchess.co.nz',
    ratingListFormat: 'html',
    scrapeStrategy: 'fetch-html',
    estPlayerCount: 2000,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'NZCF in PLAN.md',
  },
  {
    code: 'PLW',
    name: 'Palau Chess Federation',
    iso2: 'PW',
    iso3: 'PLW',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 50,
    syncCadence: 'manual',
    active: false,
  },
  {
    code: 'PNG',
    name: 'Papua New Guinea Chess Federation',
    iso2: 'PG',
    iso3: 'PNG',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 200,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SAM',
    name: 'Samoa Chess Federation',
    iso2: 'WS',
    iso3: 'WSM',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'SOL',
    name: 'Solomon Islands Chess Federation',
    iso2: 'SB',
    iso3: 'SLB',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'TAH',
    name: 'Fédération Tahitienne des Échecs',
    iso2: 'PF',
    iso3: 'PYF',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
    notes: 'French Polynesia',
  },
  {
    code: 'TGA',
    name: 'Tonga Chess Federation',
    iso2: 'TO',
    iso3: 'TON',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
  {
    code: 'TUV',
    name: 'Tuvalu Chess Federation',
    iso2: 'TV',
    iso3: 'TUV',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 50,
    syncCadence: 'manual',
    active: false,
  },
  {
    code: 'VAN',
    name: 'Vanuatu Chess Federation',
    iso2: 'VU',
    iso3: 'VUT',
    continent: 'OC',
    ratingListUrl: null,
    ratingListFormat: null,
    scrapeStrategy: 'placeholder',
    estPlayerCount: 100,
    syncCadence: 'semi_annual',
    active: false,
  },
] as const;

/** O(1) lookup. */
export const FEDERATIONS_BY_CODE: Record<string, FederationDirectoryEntry> = Object.fromEntries(
  FEDERATION_DIRECTORY.map((f) => [f.code, f]),
);

/** Total federation count — used in tests/assertions. */
export const FEDERATION_COUNT = FEDERATION_DIRECTORY.length;

/** Group by continent for UI dropdowns. */
export function groupByContinent(): Record<string, FederationDirectoryEntry[]> {
  const groups: Record<string, FederationDirectoryEntry[]> = {};
  for (const f of FEDERATION_DIRECTORY) {
    const key = f.continent ?? 'INT';
    (groups[key] ??= []).push(f);
  }
  return groups;
}

/**
 * Map FIDE alpha-3 codes that we don't use as PKs back to our canonical code.
 * Used by the `/scout/federation/[code]` route to 301-redirect FIDE-style URLs
 * (e.g. `/scout/federation/USA`) to the canonical row (`/scout/federation/USCF`).
 */
export const FIDE_CODE_ALIASES: Record<string, string> = {
  USA: 'USCF',
  ENG: 'ECF',
  GER: 'DSB',
  FRA: 'FFE',
  ITA: 'FSI',
  ISR: 'ICF',
};

/**
 * Return the canonical federation code for any of:
 *   - an existing PK in `federations.id` (passthrough)
 *   - a FIDE alpha-3 alias (USA → USCF, ENG → ECF, …)
 *   - mixed-case input (uppercase-normalized)
 */
export function canonicalFederationCode(input: string): string | null {
  const up = input.trim().toUpperCase();
  if (FEDERATIONS_BY_CODE[up]) return up;
  const aliased = FIDE_CODE_ALIASES[up];
  if (aliased && FEDERATIONS_BY_CODE[aliased]) return aliased;
  return null;
}
